<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rallip.Data\Rallip.Data.csproj" />
    <ProjectReference Include="..\Rallip.Domain.Model\Rallip.Domain.Model.csproj" />
    <ProjectReference Include="..\Rallip.DTOs\Rallip.DTOs.csproj" />
  </ItemGroup>

</Project>
